# Theme - Minimal
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

# Configuration - Basics
show_downloads: false
title: 'Eyan Documet'
description: 'Generalist Mechanical Engineer'
color-scheme: auto
logo: /assets/img/mugshot.png
favicon: true
