# Basics
title: Eyan Documet
description: Personal Website & Portfolio
logo: /assets/img/headshot_circle.png

# Theme - TODO: Implement more sophisticated theme
theme: jekyll-theme-minimal

# Analyitics stuff
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

