# Theme - Minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

# Configuration / Settings
show_downloads: false
title: "Eyan's Digital Portfolio"
description: "Generalist Mechanical Engineer, former Intern at Lawrence Berkeley National Lab"
color-scheme: auto
logo: /assets/img/mugshot.png
favicon: true
hide_project_page: true
favicon: true

# Sidebar
platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/eyandocumet
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:eyan.documet@protonmail.com
  - name: Phone
    icon: <i class="fa-solid fa-phone"></i>
    link: tel:+13194805366

# Navigation
navigation:
  - name: Home
    link: ./index.html
    navigation:
  - name: PyroBot
    link: ./pryo.html
  - name: Gyroid Experiment
    link: ./gyroid.html
  - name: Inchworm Robot
    link: ./inchworm.html
