# Theme - Minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

# Configuration - Basics
show_downloads: false
title: "Eyan's Digital Portfolio"
description: "Generalist Mechanical Engineer, former Intern at Lawrence Berkeley National Lab"
color-scheme: auto
logo: /assets/img/mugshot.png
favicon: true
