# Basics
description: Generalist Mechanical Engineer
logo: /assets/img/mugshot.png

# Theme - TODO: Implement more sophisticated theme
theme: jekyll-theme-minimal

# Analyitics stuff
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

